# Generated by Django 2.0 on 2017-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0002_exercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
