# Generated by Django 2.0 on 2017-12-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0003_auto_20171215_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='warmup_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
