# Generated by Django 2.0 on 2017-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0004_auto_20171226_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(to='inshape.Workout'),
        ),
    ]
