# Generated by Django 2.0 on 2018-03-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('inshape', '0005_auto_20171227_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Routine',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='workouts',
            new_name='routines',
        ),
    ]
