# Generated by Django 2.0 on 2018-03-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0006_auto_20180321_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='routines',
            new_name='routine',
        ),
    ]
