# Generated by Django 2.1.1 on 2018-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0009_workoutbiking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutbiking',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
