# Generated by Django 2.1.1 on 2018-09-19 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0010_auto_20180919_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 12, 56, 24, 473057)),
        ),
    ]
