# Generated by Django 2.1.1 on 2018-09-26 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0012_auto_20180919_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 21, 19, 36, 504051)),
        ),
    ]
