# Generated by Django 2.1.1 on 2018-10-19 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0014_auto_20181014_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutClimb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutclimbing',
            name='workout',
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 10, 47, 51, 441421)),
        ),
        migrations.DeleteModel(
            name='WorkoutClimbing',
        ),
        migrations.AddField(
            model_name='workoutclimb',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inshape.Workout'),
        ),
    ]
