# Generated by Django 2.1.1 on 2018-10-20 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0015_auto_20181019_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 11, 7, 8, 167534)),
        ),
    ]
