# Generated by Django 2.1.1 on 2018-11-11 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0016_auto_20181020_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('duration', models.TimeField()),
                ('avg_speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('time_in_zone', models.TimeField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 11, 16, 25, 24601)),
        ),
        migrations.AddField(
            model_name='workoutrunning',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inshape.Workout'),
        ),
    ]
