# Generated by Django 2.1.1 on 2019-03-06 02:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0018_auto_20181209_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('duration', models.TimeField()),
                ('avg_speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('time_in_zone', models.TimeField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 20, 19, 20, 4378)),
        ),
        migrations.AddField(
            model_name='workoutcardio',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inshape.Workout'),
        ),
    ]
