# Generated by Django 2.1.1 on 2021-11-23 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0020_auto_20211122_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutcardio',
            old_name='watts',
            new_name='avg_watts',
        ),
        migrations.AddField(
            model_name='workoutcardio',
            name='max_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 21, 52, 58, 847584)),
        ),
    ]
