# Generated by Django 2.1.1 on 2022-01-10 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0022_auto_20211122_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutbiking',
            name='avg_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutbiking',
            name='max_watts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 11, 8, 33, 658557)),
        ),
    ]
