# Generated by Django 4.0.2 on 2023-10-31 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshape', '0025_alter_workout_workout_date_workoutswimming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 12, 34, 51, 312594)),
        ),
    ]
